apiVersion: training.eduk8s.io/v1alpha2
kind: Workshop
metadata:
  name: lab-external-content
spec:
  title: External Content
  description: Workshop demonstrating use of external workshop content.
  vendor: eduk8s.io
  difficulty: beginner
  duration: 15m
  url: https://github.com/eduk8s-tests/lab-external-content
  content:
    files: github.com/eduk8s/lab-external-content
  session:
    namespaces:
      budget: small
    applications:
      terminal:
        enabled: true
        layout: split
      console:
        enabled: true
      editor:
        enabled: true
    env:
    - name: EXTERNAL_CONTENT
      value: https://docs.edukates.io/
